spring:
  application:
    name: auth
  redis:
    host: localhost
    port: 6379
    password: admin
temp:
  jwt:
    secret: VGhpcyBpcyBhIHRlbXBvcmFyeSBzZWNyZXQgcGFzc3dvcmQ
jwt:
  ttl:
    access: 900000 # 15M
    refresh: 3600000 # 1Day